version: "3.5"

networks:
  localdev:
    name: localdev

services:
  frontend-service:
    build: frontend/
    image: z33p/one-study:frontend_1.0.0
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - uranus-service
      - authserver-service
      - neptune-service
    networks:
      - localdev

  authserver-service:
    build: AuthServer/
    image: z33p/one-study:authserver_1.0.0
    container_name: authserver
    restart: always
    depends_on:
      - database
    networks:
      - localdev

  uranus-service:
    build: webAPIs/uranus/
    image: z33p/one-study:uranus_1.0.0
    container_name: uranus
    restart: always
    depends_on:
      - database
    networks:
      - localdev

  neptune-service:
    build: webAPIs/Neptune/
    image: z33p/one-study:neptune_1.0.0
    container_name: neptune
    restart: always
    depends_on:
      - database
    networks:
      - localdev

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - localdev
