version: "3.5"

networks:
  localdev:
    name: localdev

services:
  server:
    build: ./server
    image: one/server
    container_name: server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf --name server_volume
    depends_on:
      - frontend
      - backend
      - auth_server
      - flashcards
    networks:
      - localdev

  frontend:
    build: frontend/
    image: one/frontend
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app --name frontend_volume
    networks:
      - localdev

  backend:
    build: backend/
    image: one/backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app --name backend_volume
    depends_on:
      - backend_db
    networks:
      - localdev

  backend_db:
    image: postgres
    container_name: backend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./backend/server_data:/var/lib/postgresql/data --name backend_db_volume
    networks:
      - localdev

  auth_server:
    build: AuthServer/
    image: one/auth_server
    container_name: auth_server
    restart: always
    depends_on:
      - auth_server_db
    networks:
      - localdev

  auth_server_db:
    image: postgres
    container_name: auth_server_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./AuthServer/server_data:/var/lib/postgresql/data --name auth_server_db_volume
    networks:
      - localdev

  flashcards:
    build: FlashCards/
    image: one/flashcards
    container_name: flashcards
    restart: always
    depends_on:
      - flashcards_db
    networks:
      - localdev

  flashcards_db:
    image: postgres
    container_name: flashcards_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./FlashCards/server_data:/var/lib/postgresql/data --name flashcards_db_volume
    networks:
      - localdev
