version: "3.5"

services:
  auth_db:
    image: postgres
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./authserver.db:/var/lib/postgresql/data
